[server]
maxUploadSize = 700
maxMessageSize = 700
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1684FF"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172033"
font = "sans serif"
